/*
 * Teksten van het fundament van de planning (deel 0, ontwerp
 * busbedrijf-planning §3.4). Regel: alle `bd.fout.*`-sleutels staan hier,
 * zodat elke fout van elk deel een tekst heeft (probe-teksten.ts kijkt dat na).
 */
export const TEKST_FUNDAMENT = {
  'bd.nav.planning': { en: 'Planning', de: 'Planung', fr: 'Planning', nl: 'Planning' },
  'bd.nav.map': { en: 'Map', de: 'Karte', fr: 'Carte', nl: 'Kaart' },
  'bd.fout.geen': { en: 'There is no bus company yet.', de: 'Es gibt noch keinen Busbetrieb.', fr: 'Il n’y a pas encore de compagnie de bus.', nl: 'Er is nog geen busbedrijf.' },
  'bd.fout.weg': { en: 'That is not possible (any more).', de: 'Das geht (jetzt) nicht (mehr).', fr: 'Ce n’est plus possible.', nl: 'Dat kan nu niet (meer).' },
  'bd.fout.al': { en: 'You already have that.', de: 'Das hast du schon.', fr: 'Vous l’avez déjà.', nl: 'Dat heb je al.' },
  'bd.fout.niveau': { en: 'Your company is not at the right level for that yet.', de: 'Dein Betrieb hat dafür noch nicht die richtige Stufe.', fr: 'Votre entreprise n’a pas encore le niveau requis.', nl: 'Daarvoor is je bedrijf nog niet op het goede niveau.' },
  'bd.fout.lijn': { en: 'That line is not (or no longer) on the map.', de: 'Diese Linie ist nicht (mehr) auf der Karte.', fr: 'Cette ligne n’est pas (plus) sur la carte.', nl: 'Die lijn staat niet (meer) op de kaart.' },
  'bd.fout.kaart': { en: 'The map of this contract is not in your OMSI folder.', de: 'Die Karte dieser Konzession ist nicht in deinem OMSI-Ordner.', fr: 'La carte de cette concession n’est pas dans votre dossier OMSI.', nl: 'De kaart van deze concessie staat niet in je OMSI-map.' },
  'bd.fout.dag': { en: 'That is only possible for today.', de: 'Das geht nur für heute.', fr: 'Ce n’est possible que pour aujourd’hui.', nl: 'Dat kan alleen voor vandaag.' },
  'bd.fout.rit': { en: 'Finish or hand back your company duty first; then you can close the day.', de: 'Beende oder gib zuerst deine Betriebsfahrt zurück; dann kannst du den Tag abschließen.', fr: 'Terminez ou rendez d’abord votre service d’entreprise ; ensuite vous pourrez clôturer la journée.', nl: 'Rond eerst je bedrijfsrit af of geef hem terug; dan kun je de dag afsluiten.' },
  'bd.fout.bezet': { en: 'They are already assigned at that time.', de: 'Zu dieser Zeit ist schon jemand eingeteilt.', fr: 'Déjà affecté à ce moment-là.', nl: 'Die is op dat moment al ingedeeld.' },
  'bd.fout.te-lang': { en: 'That driver would work more than 10 hours in one day. That is not allowed.', de: 'Dann arbeitet dieser Fahrer mehr als 10 Stunden an einem Tag. Das ist nicht erlaubt.', fr: 'Ce chauffeur travaillerait plus de 10 heures en une journée. Ce n’est pas permis.', nl: 'Dan werkt die chauffeur meer dan 10 uur op één dag. Dat mag niet.' },
  'bd.fout.planner': { en: 'Only after the Scheduler course.', de: 'Erst nach der Schulung Disponent.', fr: 'Seulement après la formation Planificateur.', nl: 'Dat kan pas na de opleiding Planner.' },
  'bd.fout.geenPlek': { en: 'No free block on this line where this bus fits.', de: 'Auf dieser Linie ist kein Umlauf mehr frei, in den dieser Bus passt.', fr: 'Plus aucune rotation libre sur cette ligne pour ce bus.', nl: 'Op deze lijn is geen omloop meer vrij waar deze bus tussen past.' },
  'bd.fout.kort': { en: 'Too short notice: the subcontractor has nobody left.', de: 'Zu kurzfristig: der Subunternehmer hat niemanden mehr frei.', fr: 'Trop tard : le sous-traitant n’a plus personne.', nl: 'Te kort dag: de onderaannemer heeft niemand meer vrij.' },
  'bd.fout.vol': { en: 'The agency has nobody left today.', de: 'Die Zeitarbeitsfirma hat heute niemanden mehr.', fr: 'L’agence d’intérim n’a plus personne aujourd’hui.', nl: 'Het uitzendbureau heeft vandaag niemand meer.' },
  'bd.fout.bezig': { en: 'You are driving this duty yourself.', de: 'Diesen Dienst fährst du gerade selbst.', fr: 'Vous conduisez ce service vous-même.', nl: 'Deze dienst rijd je nu zelf.' },
  'bd.fout.gereden': { en: 'You already drove (part of) this duty today.', de: 'Diesen Dienst bist du heute schon (teilweise) gefahren.', fr: 'Vous avez déjà conduit (une partie de) ce service aujourd’hui.', nl: 'Deze dienst heb je vandaag al (deels) gereden.' },
  'bd.fout.ritBezig': { en: 'You already accepted a duty. Finish or hand it back first.', de: 'Du hast schon einen Dienst angenommen. Beende ihn oder gib ihn zuerst zurück.', fr: 'Vous avez déjà accepté un service. Terminez-le ou rendez-le d’abord.', nl: 'Je hebt al een dienst aangenomen. Rond die eerst af of geef hem terug.' },
  'bd.fout.dienst': { en: 'This duty does not exist today (any more).', de: 'Diesen Dienst gibt es heute (nicht mehr).', fr: 'Ce service n’existe pas (plus) aujourd’hui.', nl: 'Deze dienst bestaat vandaag niet (meer).' },
  'bd.fout.bus': { en: 'The bus of this block is not installed in OMSI.', de: 'Der Bus dieses Umlaufs ist in OMSI nicht installiert.', fr: 'Le bus de cette rotation n’est pas installé dans OMSI.', nl: 'De bus van deze omloop is niet geïnstalleerd in OMSI.' },
  'bd.fout.busLigt': { en: 'This block has no bus today: you let it drop. Choose a bus first.', de: 'Dieser Umlauf hat heute keinen Bus: du hast ihn ausfallen lassen. Wähle zuerst einen Bus.', fr: 'Cette rotation n’a pas de bus aujourd’hui : vous l’avez laissée tomber. Choisissez d’abord un bus.', nl: 'Deze omloop heeft vandaag geen bus: je liet hem uitvallen. Kies eerst een bus.' },
  'bd.fout.eigen': { en: 'This block runs with a bus of your own company; that one stays.', de: 'Dieser Umlauf fährt mit einem Bus deines Betriebs; der bleibt.', fr: 'Cette rotation roule avec un bus de votre entreprise ; il reste.', nl: 'Deze omloop rijdt met een bus van je eigen bedrijf; die blijft.' },
  'bd.fout.gestart': { en: 'The duty has already started; the bus can no longer be changed.', de: 'Der Dienst läuft schon; der Bus lässt sich nicht mehr ändern.', fr: 'Le service a déjà commencé ; le bus ne peut plus être changé.', nl: 'De dienst is al begonnen; de bus kan niet meer anders.' },
  'bd.fout.venster': { en: 'Choose a first and a last trip within the duty.', de: 'Wähle eine erste und eine letzte Fahrt innerhalb des Dienstes.', fr: 'Choisissez un premier et un dernier trajet dans le service.', nl: 'Kies een eerste en een laatste rit binnen de dienst.' },
  'bd.kind.eigen-bus': { en: 'Own buses (fuel and insurance)', de: 'Eigene Busse (Kraftstoff und Versicherung)', fr: 'Bus propres (carburant et assurance)', nl: 'Eigen bussen (brandstof en verzekering)' },
  'bd.kind.uitzend': { en: 'Agency drivers', de: 'Leihfahrer', fr: 'Chauffeurs intérimaires', nl: 'Uitzendkrachten' },
  'bd.kind.huurbus': { en: 'Replacement buses', de: 'Ersatzbusse', fr: 'Bus de remplacement', nl: 'Vervangende bussen' },
  'bd.kind.boete': { en: 'Fine from the authority', de: 'Vertragsstrafe des Aufgabenträgers', fr: 'Pénalité de l’autorité', nl: 'Boete opdrachtgever' },
  'bd.kind.overuren': { en: 'Overtime', de: 'Überstunden', fr: 'Heures supplémentaires', nl: 'Overuren' },
  'bd.kind.pech': { en: 'Breakdown (towing and parts)', de: 'Panne (Abschleppen und Teile)', fr: 'Panne (remorquage et pièces)', nl: 'Pech (sleepdienst en onderdelen)' },
  'bd.dag.ma': { en: 'Mon', de: 'Mo', fr: 'lun', nl: 'ma' },
  'bd.dag.di': { en: 'Tue', de: 'Di', fr: 'mar', nl: 'di' },
  'bd.dag.wo': { en: 'Wed', de: 'Mi', fr: 'mer', nl: 'wo' },
  'bd.dag.do': { en: 'Thu', de: 'Do', fr: 'jeu', nl: 'do' },
  'bd.dag.vr': { en: 'Fri', de: 'Fr', fr: 'ven', nl: 'vr' },
  'bd.dag.za': { en: 'Sat', de: 'Sa', fr: 'sam', nl: 'za' },
  'bd.dag.zo': { en: 'Sun', de: 'So', fr: 'dim', nl: 'zo' },
  'bd.dag.feest': { en: 'public holiday', de: 'Feiertag', fr: 'jour férié', nl: 'feestdag' },
  'bd.masker.school': { en: 'school days only', de: 'nur Schultage', fr: 'jours d’école seulement', nl: 'alleen schooldagen' },
  'bd.masker.break': { en: 'school holidays only', de: 'nur Ferien', fr: 'vacances seulement', nl: 'alleen vakantie' },
  'bd.vorm.midi': { en: 'midibus', de: 'Midibus', fr: 'midibus', nl: 'midibus' },
  'bd.vorm.solo': { en: 'standard bus', de: 'Solobus', fr: 'bus standard', nl: 'solobus' },
  'bd.vorm.geleed': { en: 'articulated bus', de: 'Gelenkbus', fr: 'bus articulé', nl: 'gelede bus' },
  'bd.vorm.dubbel': { en: 'double-decker', de: 'Doppeldecker', fr: 'bus à impériale', nl: 'dubbeldekker' },
  'tb.msg.uitgevallen.t': { en: '{uren} timetable hours dropped', de: '{uren} Fahrplanstunden sind ausgefallen', fr: '{uren} heures de service ont été perdues', nl: '{uren} dienstregelingsuren vielen uit' },
  'tb.msg.uitgevallen.b': { en: 'From the authority: {ritten} trips were not run. The fine is {boete}, and it costs reputation.', de: 'Vom Aufgabenträger: {ritten} Fahrten wurden nicht gefahren. Die Vertragsstrafe beträgt {boete}, und es kostet Ruf.', fr: 'De l’autorité : {ritten} trajets n’ont pas été assurés. La pénalité est de {boete}, et cela coûte de la réputation.', nl: 'Van de opdrachtgever: {ritten} ritten zijn niet gereden. De boete is {boete}, en het kost reputatie.' },
  'tb.msg.rooster.t': { en: 'New: your roster', de: 'Neu: dein Dienstplan', fr: 'Nouveau : votre planning', nl: 'Nieuw: je rooster' },
  'tb.msg.rooster.b': {
    en: 'From now on the company plans each day from the real timetable of the map. The authority pays per timetable hour actually run that day: {uren} h today. Before, the app counted {oud} h, all day types together. {bussen} buses and {diensten} duties are already assigned; what stays empty is subcontracted. Have a look in Planning.',
    de: 'Ab jetzt plant der Betrieb jeden Tag aus dem echten Fahrplan der Karte. Der Aufgabenträger zahlt pro gefahrener Fahrplanstunde dieses Tages: heute {uren} h. Vorher zählte die App {oud} h, alle Tagesarten zusammen. {bussen} Busse und {diensten} Dienste sind schon eingeteilt; was leer bleibt, wird fremdvergeben. Schau in Planung.',
    fr: 'Désormais l’entreprise planifie chaque jour à partir du vrai horaire de la carte. L’autorité paie par heure de service réellement assurée ce jour-là : {uren} h aujourd’hui. Avant, l’application comptait {oud} h, tous types de jours confondus. {bussen} bus et {diensten} services sont déjà affectés ; ce qui reste vide est sous-traité. Regardez dans Planning.',
    nl: 'Vanaf nu plant het bedrijf per dag uit de echte dienstregeling van de kaart. De opdrachtgever betaalt per gereden dienstregelingsuur van die dag: vandaag {uren} u. Eerder telde de app {oud} u, alle dagsoorten bij elkaar. {bussen} bussen en {diensten} diensten zijn al ingedeeld; wat leeg blijft, besteedt het bedrijf uit. Kijk in Planning.'
  },
  'tb.msg.vorm.t': { en: 'Bus {nummer} is a {vorm}', de: 'Bus {nummer} ist ein {vorm}', fr: 'Le bus {nummer} est un {vorm}', nl: 'Bus {nummer} is een {vorm}' },
  'tb.msg.vorm.b': {
    en: 'OMSI couples a trailer to it, but the app counted it as a standard bus. Value and planning now use a {vorm}.',
    de: 'OMSI kuppelt einen Anhänger an, aber die App zählte ihn als Solobus. Wert und Planung rechnen jetzt mit einem {vorm}.',
    fr: 'OMSI y attelle une remorque, mais l’application le comptait comme bus standard. La valeur et le planning utilisent maintenant un {vorm}.',
    nl: 'OMSI koppelt er een aanhanger aan, maar de app telde hem als solobus. Waarde en planning rekenen nu met een {vorm}.'
  }
} as const satisfies Record<string, { en: string; de: string; fr: string; nl: string }>
