/*
 * Teksten van de planning, deel A (ontwerp busbedrijf-planning §4.4): het
 * planscherm, het dashboard, de concessies, het personeel en de busmarkt. De
 * sleutels `bd.fout.*` staan in fundament.ts.
 */
export const TEKST_PLANNING = {
  'bd.plan.titel': { en: 'Planning · day {dag} · {datum}', de: 'Planung · Tag {dag} · {datum}', fr: 'Planning · jour {dag} · {datum}', nl: 'Planning · dag {dag} · {datum}' },
  'bd.plan.soort.school': { en: 'school day', de: 'Schultag', fr: 'jour scolaire', nl: 'schooldag' },
  'bd.plan.soort.break': { en: 'school holidays', de: 'Schulferien', fr: 'vacances scolaires', nl: 'schoolvakantie' },
  'bd.plan.soort.holiday': { en: 'public holiday', de: 'Feiertag', fr: 'jour férié', nl: 'feestdag' },
  'bd.plan.geld': { en: 'Today: revenue {vergoeding} · costs {kosten} · result {resultaat}', de: 'Heute: Vergütung {vergoeding} · Kosten {kosten} · Ergebnis {resultaat}', fr: 'Aujourd’hui : recettes {vergoeding} · coûts {kosten} · résultat {resultaat}', nl: 'Vandaag: vergoeding {vergoeding} · kosten {kosten} · resultaat {resultaat}' },
  'bd.plan.geldToekomst': { en: 'Expected on {datum}: result {resultaat}', de: 'Erwartet am {datum}: Ergebnis {resultaat}', fr: 'Prévu le {datum} : résultat {resultaat}', nl: 'Verwacht op {datum}: resultaat {resultaat}' },
  'bd.plan.week': { en: 'This week', de: 'Diese Woche', fr: 'Cette semaine', nl: 'Deze week' },
  'bd.plan.weekDag': { en: '{dag} {nr} · {eigen}/{diensten}', de: '{dag} {nr} · {eigen}/{diensten}', fr: '{dag} {nr} · {eigen}/{diensten}', nl: '{dag} {nr} · {eigen}/{diensten}' },
  'bd.plan.vulAan': { en: 'Fill up', de: 'Auffüllen', fr: 'Compléter', nl: 'Vul aan' },
  'bd.plan.vulAanDag': { en: 'Only this day', de: 'Nur diesen Tag', fr: 'Ce jour seulement', nl: 'Alleen deze dag' },
  'bd.plan.vulAanWeek': { en: 'The whole week', de: 'Die ganze Woche', fr: 'Toute la semaine', nl: 'De hele week' },
  'bd.plan.vulAanKlaar': { en: '{bussen} buses and {diensten} duties assigned.', de: '{bussen} Busse und {diensten} Dienste eingeteilt.', fr: '{bussen} bus et {diensten} services affectés.', nl: '{bussen} bussen en {diensten} diensten ingedeeld.' },
  'bd.plan.leegmaken': { en: 'Clear roster', de: 'Dienstplan leeren', fr: 'Vider le planning', nl: 'Rooster leegmaken' },
  'bd.plan.leegMasker': { en: 'Only {masker}', de: 'Nur {masker}', fr: 'Seulement {masker}', nl: 'Alleen {masker}' },
  'bd.plan.leegAlles': { en: 'Everything', de: 'Alles', fr: 'Tout', nl: 'Alles' },
  'bd.plan.leegVraag': { en: 'Remove {n} assignments? You can undo it afterwards.', de: '{n} Einteilungen entfernen? Du kannst es danach rückgängig machen.', fr: 'Retirer {n} affectations ? Vous pourrez annuler ensuite.', nl: '{n} indelingen weghalen? Je kunt het daarna nog ongedaan maken.' },
  'bd.plan.ongedaan': { en: 'Undo', de: 'Rückgängig', fr: 'Annuler', nl: 'Ongedaan maken' },
  'bd.plan.ongedaanKlaar': { en: 'Roster restored.', de: 'Dienstplan wiederhergestellt.', fr: 'Planning rétabli.', nl: 'Rooster teruggezet.' },
  'bd.plan.auto': { en: 'Fill up by itself every new day', de: 'Jeden neuen Tag selbst auffüllen', fr: 'Compléter tout seul chaque nouveau jour', nl: 'Elke nieuwe dag zelf aanvullen' },
  'bd.plan.autoPlanner': { en: 'Possible after the Scheduler course.', de: 'Möglich nach der Schulung Disponent.', fr: 'Possible après la formation Planificateur.', nl: 'Kan na de opleiding Planner.' },
  'bd.plan.weergave.omlopen': { en: 'By block', de: 'Nach Umlauf', fr: 'Par rotation', nl: 'Per omloop' },
  'bd.plan.weergave.mensen': { en: 'People and buses', de: 'Personal und Busse', fr: 'Personnel et bus', nl: 'Mensen en bussen' },
  'bd.plan.zoomIn': { en: 'Zoom in', de: 'Vergrößern', fr: 'Zoom avant', nl: 'Inzoomen' },
  'bd.plan.zoomUit': { en: 'Zoom out', de: 'Verkleinern', fr: 'Zoom arrière', nl: 'Uitzoomen' },
  'bd.plan.telling': { en: '{n} duties · {eigen} own · {jij} you · {uitzend} agency · {uitbesteed} subcontracted · {open} open', de: '{n} Dienste · {eigen} eigene · {jij} du · {uitzend} Zeitarbeit · {uitbesteed} fremdvergeben · {open} offen', fr: '{n} services · {eigen} propres · {jij} vous · {uitzend} intérim · {uitbesteed} sous-traités · {open} ouverts', nl: '{n} diensten · {eigen} eigen · {jij} jij · {uitzend} uitzend · {uitbesteed} uitbesteed · {open} open' },
  'bd.plan.omlopenTelling': { en: '{n} blocks · {eigen} with an own bus', de: '{n} Umläufe · {eigen} mit eigenem Bus', fr: '{n} rotations · {eigen} avec un bus propre', nl: '{n} omlopen · {eigen} met eigen bus' },
  'bd.plan.conflicten': { en: '{n} conflicts', de: '{n} Konflikte', fr: '{n} conflits', nl: '{n} conflicten' },
  'bd.plan.toonAlles': { en: 'Show all', de: 'Alles zeigen', fr: 'Tout afficher', nl: 'Alles tonen' },
  'bd.plan.omloop': { en: 'Block {nr}', de: 'Umlauf {nr}', fr: 'Rotation {nr}', nl: 'Omloop {nr}' },
  'bd.plan.geldtVoor': { en: 'applies to {masker}', de: 'gilt für {masker}', fr: 'valable {masker}', nl: 'geldt voor {masker}' },
  'bd.plan.busVak': { en: 'Drop a bus here', de: 'Zieh einen Bus hierher', fr: 'Déposez un bus ici', nl: 'Sleep een bus hierheen' },
  'bd.plan.busVakUitleg': { en: 'Without an own bus, the subcontractor drives this block with his own bus.', de: 'Ohne eigenen Bus fährt der Subunternehmer diesen Umlauf mit seinem eigenen Bus.', fr: 'Sans bus propre, le sous-traitant assure cette rotation avec son propre bus.', nl: 'Zonder eigen bus rijdt de onderaannemer deze omloop met zijn eigen bus.' },
  'bd.plan.busKopen': { en: 'Buy a bus', de: 'Bus kaufen', fr: 'Acheter un bus', nl: 'Bus kopen' },
  'bd.plan.busBespaart': { en: 'own bus saves {geld}', de: 'eigener Bus spart {geld}', fr: 'un bus propre économise {geld}', nl: 'eigen bus bespaart {geld}' },
  'bd.plan.uitbesteed': { en: 'Subcontracted', de: 'Fremdvergeben', fr: 'Sous-traité', nl: 'Uitbesteed' },
  'bd.plan.jij': { en: 'You', de: 'Du', fr: 'Vous', nl: 'Jij' },
  'bd.plan.rijdtNu': { en: 'Driving now (you)', de: 'Fährt gerade (du)', fr: 'En route (vous)', nl: 'Rijdt nu (jij)' },
  'bd.plan.uitzend': { en: 'Agency', de: 'Zeitarbeit', fr: 'Intérim', nl: 'Uitzend' },
  'bd.plan.centrale': { en: 'dispatch', de: 'Leitstelle', fr: 'régulation', nl: 'centrale' },
  'bd.plan.open': { en: 'OPEN · {reden}', de: 'OFFEN · {reden}', fr: 'OUVERT · {reden}', nl: 'OPEN · {reden}' },
  'bd.plan.reden.ziek': { en: 'sick', de: 'krank', fr: 'malade', nl: 'ziek' },
  'bd.plan.reden.telaat': { en: 'late', de: 'verspätet', fr: 'en retard', nl: 'te laat' },
  'bd.plan.reden.pech': { en: 'breakdown', de: 'Panne', fr: 'panne', nl: 'pech' },
  'bd.plan.valtUit': { en: 'Dropped', de: 'Fällt aus', fr: 'Supprimé', nl: 'Valt uit' },
  'bd.plan.huur': { en: 'Hired bus', de: 'Mietbus', fr: 'Bus loué', nl: 'Huurbus' },
  'bd.plan.wie.eigen': { en: 'own driver', de: 'eigener Fahrer', fr: 'chauffeur propre', nl: 'eigen chauffeur' },
  'bd.plan.wie.collega': { en: 'colleague', de: 'Kollege', fr: 'collègue', nl: 'collega' },
  'bd.plan.vrij': { en: 'Free today', de: 'Heute frei', fr: 'Libres aujourd’hui', nl: 'Vrij vandaag' },
  'bd.plan.vrijUitleg': { en: 'Whoever is free steps in first when someone drops out.', de: 'Wer frei ist, springt bei Ausfall als Erstes ein.', fr: 'Qui est libre remplace en premier en cas d’absence.', nl: 'Wie vrij is, springt bij uitval als eerste in.' },
  'bd.plan.chauffeurs': { en: 'Drivers', de: 'Fahrer', fr: 'Chauffeurs', nl: 'Chauffeurs' },
  'bd.plan.bussen': { en: 'Buses', de: 'Busse', fr: 'Bus', nl: 'Bussen' },
  'bd.plan.chauffeurWerk': { en: '{uren} h work · saves {bespaart} · wage {loon}', de: '{uren} Std Arbeit · spart {bespaart} · Lohn {loon}', fr: '{uren} h de travail · économise {bespaart} · salaire {loon}', nl: '{uren} u werk · bespaart {bespaart} · loon {loon}' },
  'bd.plan.chauffeurVrij': { en: 'no duty · wage {loon}', de: 'kein Dienst · Lohn {loon}', fr: 'pas de service · salaire {loon}', nl: 'geen dienst · loon {loon}' },
  'bd.plan.ziekTot': { en: 'sick until day {dag}', de: 'krank bis Tag {dag}', fr: 'malade jusqu’au jour {dag}', nl: 'ziek t/m dag {dag}' },
  'bd.plan.cursus': { en: 'on a course', de: 'auf Schulung', fr: 'en formation', nl: 'op cursus' },
  'bd.plan.busStaat': { en: 'condition {staat} · breakdown risk {kans}%', de: 'Zustand {staat} · Pannenrisiko {kans} %', fr: 'état {staat} · risque de panne {kans} %', nl: 'staat {staat} · pechkans {kans}%' },
  'bd.plan.werkplaats': { en: 'workshop', de: 'Werkstatt', fr: 'atelier', nl: 'werkplaats' },
  'bd.plan.nietGeinstalleerd': { en: 'not installed in OMSI', de: 'nicht in OMSI installiert', fr: 'pas installé dans OMSI', nl: 'niet geïnstalleerd in OMSI' },
  'bd.plan.dienst': { en: 'Duty {omloop}-{deel}', de: 'Dienst {omloop}-{deel}', fr: 'Service {omloop}-{deel}', nl: 'Dienst {omloop}-{deel}' },
  'bd.plan.dienstRegel': { en: 'Line {lijn} · {van}–{tot} · working time {werk} h · paid {betaald} h · {ritten} trips', de: 'Linie {lijn} · {van}–{tot} · Arbeitszeit {werk} Std · bezahlt {betaald} Std · {ritten} Fahrten', fr: 'Ligne {lijn} · {van}–{tot} · temps de travail {werk} h · payé {betaald} h · {ritten} trajets', nl: 'Lijn {lijn} · {van}–{tot} · werktijd {werk} u · betaald {betaald} u · {ritten} ritten' },
  'bd.plan.dienstKosten': { en: 'Costs today {geld} ({wie})', de: 'Kostet heute {geld} ({wie})', fr: 'Coûte aujourd’hui {geld} ({wie})', nl: 'Kost vandaag {geld} ({wie})' },
  'bd.plan.stuk': { en: 'Late start {van}–{tot}: {wie}', de: 'Verspäteter Beginn {van}–{tot}: {wie}', fr: 'Début en retard {van}–{tot} : {wie}', nl: 'Te-laat-stuk {van}–{tot}: {wie}' },
  'bd.plan.vanNaar': { en: 'From {van} to {naar}', de: 'Von {van} nach {naar}', fr: 'De {van} à {naar}', nl: 'Van {van} naar {naar}' },
  'bd.plan.chauffeur': { en: 'Driver', de: 'Fahrer', fr: 'Chauffeur', nl: 'Chauffeur' },
  'bd.plan.busOmloop': { en: 'Bus (whole block)', de: 'Bus (ganzer Umlauf)', fr: 'Bus (toute la rotation)', nl: 'Bus (hele omloop)' },
  'bd.plan.uitRooster': { en: 'Remove from roster', de: 'Aus dem Dienstplan nehmen', fr: 'Retirer du planning', nl: 'Uit het rooster halen' },
  'bd.plan.kiesPlek': { en: 'Tap a duty to assign {naam}.', de: 'Tippe auf einen Dienst, um {naam} einzuteilen.', fr: 'Touchez un service pour y affecter {naam}.', nl: 'Tik op een dienst om {naam} in te delen.' },
  'bd.plan.kiesOmloop': { en: 'Tap a block to assign bus {bus}.', de: 'Tippe auf einen Umlauf, um Bus {bus} einzuteilen.', fr: 'Touchez une rotation pour y affecter le bus {bus}.', nl: 'Tik op een omloop om bus {bus} in te delen.' },
  'bd.plan.annuleer': { en: 'Cancel', de: 'Abbrechen', fr: 'Annuler', nl: 'Annuleren' },
  'bd.plan.sluit': { en: 'Close', de: 'Schließen', fr: 'Fermer', nl: 'Sluiten' },
  'bd.plan.kopieer': { en: 'Copy roster from {masker}', de: 'Dienstplan von {masker} übernehmen', fr: 'Reprendre le planning de {masker}', nl: 'Rooster overnemen van {masker}' },
  'bd.plan.leegMaskerMelding': { en: '{masker} has no roster yet: {bussen} buses and {mensen} drivers would stand idle.', de: '{masker} hat noch keinen Dienstplan: {bussen} Busse und {mensen} Fahrer stehen dann still.', fr: '{masker} n’a pas encore de planning : {bussen} bus et {mensen} chauffeurs resteraient inactifs.', nl: '{masker} heeft nog geen rooster: {bussen} bussen en {mensen} chauffeurs staan dan stil.' },
  'bd.plan.buiten': { en: 'Driven outside the plan: {uren} h (counts as stand-in hours).', de: 'Außerhalb der Planung gefahren: {uren} Std (zählt als Aushilfsstunden).', fr: 'Conduit hors planning : {uren} h (compte comme heures de remplacement).', nl: 'Buiten de planning gereden: {uren} u (telt als invaluren).' },
  'bd.plan.toekomst': { en: 'Looking ahead: you are changing the fixed roster. Absences and stand-ins only show on the day itself.', de: 'Vorausschau: Du änderst den festen Dienstplan. Ausfälle und Vertretungen siehst du erst am Tag selbst.', fr: 'Anticipation : vous modifiez le planning fixe. Absences et remplacements n’apparaissent que le jour même.', nl: 'Vooruitkijken: je past het vaste rooster aan. Uitval en invullen zie je pas op de dag zelf.' },
  'bd.plan.terugVandaag': { en: 'Back to today', de: 'Zurück zu heute', fr: 'Retour à aujourd’hui', nl: 'Terug naar vandaag' },
  'bd.plan.uitleg': { en: 'A block is the day of one bus; a duty is the part one driver drives of it, at most 9.5 hours. The client pays per timetable hour; a subcontracted driver costs per working hour.', de: 'Ein Umlauf ist der Tag eines Busses; ein Dienst ist das Stück, das ein Fahrer davon fährt, höchstens 9,5 Stunden. Der Auftraggeber zahlt pro Fahrplanstunde; ein fremdvergebener Fahrer kostet pro Arbeitsstunde.', fr: 'Une rotation est la journée d’un bus ; un service est la part qu’un chauffeur en conduit, 9,5 heures au plus. Le donneur d’ordre paie par heure d’horaire ; un chauffeur sous-traité coûte par heure de travail.', nl: 'Een omloop is de dag van één bus; een dienst is het stuk dat één chauffeur ervan rijdt, hoogstens 9,5 uur. De opdrachtgever betaalt per dienstregelingsuur; een uitbestede chauffeur kost per werkuur.' },
  'bd.plan.begrepen': { en: 'Got it', de: 'Verstanden', fr: 'Compris', nl: 'Begrepen' },
  'bd.plan.geenConcessie': { en: 'No contracts yet. Bid for a line; then the app builds the roster here from the map’s timetable.', de: 'Noch keine Konzessionen. Bewirb dich auf eine Linie; dann erstellt die App hier den Dienstplan aus dem Fahrplan der Karte.', fr: 'Pas encore de concessions. Candidatez pour une ligne ; l’application construit alors ici le planning à partir des horaires de la carte.', nl: 'Nog geen concessies. Schrijf je in op een lijn; dan maakt de app hier het rooster uit de dienstregeling van de kaart.' },
  'bd.plan.naarConcessies': { en: 'To contracts', de: 'Zu den Konzessionen', fr: 'Vers les concessions', nl: 'Naar concessies' },
  'bd.plan.kaartWeg': { en: 'Map {kaart} is not in your OMSI folder. This contract is settled the old way today, without a roster.', de: 'Die Karte {kaart} ist nicht in deinem OMSI-Ordner. Diese Konzession rechnet heute wie früher, ohne Dienstplan.', fr: 'La carte {kaart} n’est pas dans votre dossier OMSI. Cette concession est calculée aujourd’hui comme avant, sans planning.', nl: 'Kaart {kaart} staat niet in je OMSI-map. Deze concessie rekent vandaag zoals vroeger, zonder rooster.' },
  'bd.plan.rijdtNiet': { en: 'Line {lijn} does not run today ({soort}).', de: 'Linie {lijn} fährt heute nicht ({soort}).', fr: 'La ligne {lijn} ne circule pas aujourd’hui ({soort}).', nl: 'Lijn {lijn} rijdt vandaag ({soort}) niet.' },
  'bd.plan.geenPersoneel': { en: 'Nobody employed yet: every duty is subcontracted.', de: 'Noch niemand angestellt: jeder Dienst wird fremdvergeben.', fr: 'Personne d’employé : chaque service est sous-traité.', nl: 'Nog niemand in dienst: elke dienst wordt uitbesteed.' },
  'bd.plan.geenBussen': { en: 'No buses yet: every block runs with a subcontractor’s bus.', de: 'Noch keine Busse: jeder Umlauf fährt mit einem Bus des Subunternehmers.', fr: 'Pas encore de bus : chaque rotation roule avec un bus du sous-traitant.', nl: 'Nog geen bussen: elke omloop rijdt met een bus van de onderaannemer.' },
  'bd.plan.nieuw': { en: 'New: your roster. Assign your buses and drivers to the blocks; whatever stays empty is subcontracted.', de: 'Neu: dein Dienstplan. Teile deine Busse und Fahrer den Umläufen zu; was leer bleibt, wird fremdvergeben.', fr: 'Nouveau : votre planning. Affectez vos bus et chauffeurs aux rotations ; ce qui reste vide est sous-traité.', nl: 'Nieuw: je rooster. Deel je bussen en chauffeurs in op de omlopen; wat leeg blijft, besteedt het bedrijf uit.' },
  'bd.plan.toursToday': { en: '{tours} blocks · {hours} h today', de: '{tours} Umläufe · {hours} Std heute', fr: '{tours} rotations · {hours} h aujourd’hui', nl: '{tours} omlopen · {hours} u vandaag' },
  'bd.plan.weekCijfers': { en: '{rituren} h a day on average · {omlopen} blocks on busy days', de: '{rituren} Std pro Tag im Schnitt · {omlopen} Umläufe an vollen Tagen', fr: '{rituren} h par jour en moyenne · {omlopen} rotations les jours chargés', nl: '{rituren} u per dag gemiddeld · {omlopen} omlopen op drukke dagen' },
  'bd.plan.concessieDag': { en: '± {geld} a day subcontracted', de: '± {geld} pro Tag fremdvergeben', fr: '± {geld} par jour en sous-traitance', nl: '± {geld} per dag uitbesteed' },
  'bd.plan.inschrijfUitleg': { en: 'Bidding costs {vast} plus {per} per block on the busiest day.', de: 'Die Bewerbung kostet {vast} plus {per} pro Umlauf am vollsten Tag.', fr: 'La candidature coûte {vast} plus {per} par rotation le jour le plus chargé.', nl: 'Inschrijven kost {vast} plus {per} per omloop op de drukste dag.' },
  'bd.plan.sollicitantLoont': { en: 'On an average duty ({uren} h), {naam} saves {bespaart} a day; wage {loon}.', de: 'Bei einem durchschnittlichen Dienst ({uren} Std) spart {naam} {bespaart} pro Tag; Lohn {loon}.', fr: 'Sur un service moyen ({uren} h), {naam} économise {bespaart} par jour ; salaire {loon}.', nl: 'Op een gemiddelde dienst ({uren} u) bespaart {naam} {bespaart} per dag; loon {loon}.' },
  'bd.plan.busLoont': { en: 'On an average block ({uren} h) this bus saves {bespaart} a day: paid back in {dagen} days.', de: 'Bei einem durchschnittlichen Umlauf ({uren} Std) spart dieser Bus {bespaart} pro Tag: amortisiert in {dagen} Tagen.', fr: 'Sur une rotation moyenne ({uren} h), ce bus économise {bespaart} par jour : remboursé en {dagen} jours.', nl: 'Op een gemiddelde omloop ({uren} u) bespaart deze bus {bespaart} per dag: terug in {dagen} dagen.' },
  'bd.plan.stilBus': { en: 'Bus {bus} is not on the roster today.', de: 'Bus {bus} steht heute nicht im Dienstplan.', fr: 'Le bus {bus} n’est pas au planning aujourd’hui.', nl: 'Bus {bus} staat vandaag niet in het rooster.' },
  'bd.plan.stilChauffeur': { en: '{naam} has no duty today.', de: '{naam} hat heute keinen Dienst.', fr: '{naam} n’a pas de service aujourd’hui.', nl: '{naam} heeft vandaag geen dienst.' },
  'bd.plan.naarPlanning': { en: 'To planning', de: 'Zur Planung', fr: 'Vers le planning', nl: 'Naar planning' },
  'bd.plan.personeelSamenvatting': { en: 'Today {eigen} duties with own drivers, {uitbesteed} subcontracted.', de: 'Heute {eigen} Dienste mit eigenen Fahrern, {uitbesteed} fremdvergeben.', fr: 'Aujourd’hui {eigen} services avec vos chauffeurs, {uitbesteed} sous-traités.', nl: 'Vandaag {eigen} diensten met eigen chauffeurs, {uitbesteed} uitbesteed.' },
  'bd.plan.uitbesteedRij': { en: 'Subcontracted ({n})', de: 'Fremdvergeben ({n})', fr: 'Sous-traités ({n})', nl: 'Uitbesteed ({n})' },
  'bd.plan.lijnDrop': { en: 'Drop a bus on the line: the app picks the best free block.', de: 'Lass einen Bus auf die Linie fallen: die App wählt den besten freien Umlauf.', fr: 'Déposez un bus sur la ligne : l’application choisit la meilleure rotation libre.', nl: 'Laat een bus op de lijn vallen: de app kiest de beste vrije omloop.' },
  'bd.plan.conflictOpen': { en: '{n} duties are open today or have a conflict', de: 'Heute sind {n} Dienste offen oder haben einen Konflikt', fr: '{n} services sont ouverts aujourd’hui ou en conflit', nl: '{n} diensten staan vandaag open of hebben een conflict' },
  'bd.plan.c.bus-weg': { en: 'Bus {bus} is no longer yours.', de: 'Bus {bus} gehört dir nicht mehr.', fr: 'Le bus {bus} n’est plus à vous.', nl: 'Bus {bus} is niet meer van jou.' },
  'bd.plan.c.bus-werkplaats': { en: 'Bus {bus} cannot go out today (workshop, worn or damaged).', de: 'Bus {bus} kann heute nicht ausrücken (Werkstatt, verschlissen oder beschädigt).', fr: 'Le bus {bus} ne peut pas sortir aujourd’hui (atelier, usé ou endommagé).', nl: 'Bus {bus} kan vandaag niet uitrijden (werkplaats, versleten of beschadigd).' },
  'bd.plan.c.bus-dubbel': { en: 'Bus {bus} is also on block {andere}, and they overlap.', de: 'Bus {bus} steht auch auf Umlauf {andere}, und die überschneiden sich.', fr: 'Le bus {bus} est aussi sur la rotation {andere}, et elles se chevauchent.', nl: 'Bus {bus} staat ook op omloop {andere}, en die overlappen.' },
  'bd.plan.c.bus-vorm': { en: 'This block asks for a {vorm}; bus {bus} is a {busvorm}.', de: 'Dieser Umlauf verlangt einen {vorm}; Bus {bus} ist ein {busvorm}.', fr: 'Cette rotation demande un {vorm} ; le bus {bus} est un {busvorm}.', nl: 'Deze omloop vraagt een {vorm}; bus {bus} is een {busvorm}.' },
  'bd.plan.c.chauffeur-weg': { en: 'This driver no longer works here.', de: 'Dieser Fahrer arbeitet hier nicht mehr.', fr: 'Ce chauffeur ne travaille plus ici.', nl: 'Deze chauffeur werkt hier niet meer.' },
  'bd.plan.c.chauffeur-afwezig': { en: '{naam} is not here today (sick or on a course); the duty is subcontracted.', de: '{naam} ist heute nicht da (krank oder auf Schulung); der Dienst wird fremdvergeben.', fr: '{naam} est absent aujourd’hui (malade ou en formation) ; le service est sous-traité.', nl: '{naam} is er vandaag niet (ziek of op cursus); de dienst wordt uitbesteed.' },
  'bd.plan.c.chauffeur-dubbel': { en: '{naam} is already driving duty {andere} then.', de: '{naam} fährt dann schon Dienst {andere}.', fr: '{naam} assure déjà le service {andere} à ce moment.', nl: '{naam} rijdt dan al dienst {andere}.' },
  'bd.plan.c.chauffeur-rust': { en: '{naam} has only {min} minutes between two duties.', de: '{naam} hat nur {min} Minuten zwischen zwei Diensten.', fr: '{naam} n’a que {min} minutes entre deux services.', nl: '{naam} heeft maar {min} minuten tussen twee diensten.' },
  'bd.plan.c.chauffeur-overstap': { en: '{naam} has to get from {van} to {naar} in {min} minutes.', de: '{naam} muss in {min} Minuten von {van} nach {naar}.', fr: '{naam} doit aller de {van} à {naar} en {min} minutes.', nl: '{naam} moet in {min} minuten van {van} naar {naar}.' },
  'bd.plan.c.chauffeur-nachtrust': { en: '{naam} has only {uren} h of rest between two working days.', de: '{naam} hat nur {uren} Std Ruhe zwischen zwei Arbeitstagen.', fr: '{naam} n’a que {uren} h de repos entre deux jours de travail.', nl: '{naam} heeft maar {uren} u rust tussen twee werkdagen.' },
  'bd.plan.c.overuren': { en: '{naam} works {uren} h of overtime (one and a half times the wage).', de: '{naam} macht {uren} Std Überstunden (anderthalbfacher Lohn).', fr: '{naam} fait {uren} h supplémentaires (une fois et demie le salaire).', nl: '{naam} maakt {uren} u overuren (anderhalf keer loon).' },
  'bd.plan.c.te-lang': { en: '{naam} would work {uren} h; more than 10 h is not allowed.', de: '{naam} würde {uren} Std arbeiten; mehr als 10 Std sind nicht erlaubt.', fr: '{naam} travaillerait {uren} h ; plus de 10 h n’est pas permis.', nl: '{naam} zou {uren} u werken; meer dan 10 u mag niet.' },
  'bd.plan.c.bevoegd': { en: '{naam} has little experience for a {vorm} (less than {n}); expect more delay.', de: '{naam} hat wenig Erfahrung für einen {vorm} (weniger als {n}); rechne mit mehr Verspätung.', fr: '{naam} a peu d’expérience pour un {vorm} (moins de {n}) ; prévoyez plus de retard.', nl: '{naam} heeft weinig ervaring voor een {vorm} (minder dan {n}); reken op meer vertraging.' },
  'bd.plan.c.monteur': { en: '{naam} is a mechanic and does not drive duties.', de: '{naam} ist Mechaniker und fährt keine Dienste.', fr: '{naam} est mécanicien et ne conduit pas de services.', nl: '{naam} is monteur en rijdt geen diensten.' }
} as const satisfies Record<string, { en: string; de: string; fr: string; nl: string }>
